export const SET_TEAM_DATA = '[LISTING] SET_TEAM_DATA';
export const BLOG_LIST_REQUESTED = 'BLOG_LIST_REQUESTED';
export const BLOG_DETAIL_REQUESTED = 'BLOG_DETAIL_REQUESTED';
export const BLOG_DELETE_REQUESTED = 'BLOG_DELETE_REQUESTED';
export const BLOG_LIST_LOADED = 'BLOG_LIST_LOADED';
export const BLOG_DETAIL_LOADED = 'BLOG_DETAIL_LOADED';
export const API_ERRORED = 'API_ERRORED';
