export const SET_TEAM_DATA = '[LISTING] SET_TEAM_DATA';
export const BLOG_DATA_REQUESTED = 'BLOG_DATA_REQUESTED';
export const BLOG_DATA_DELETED = 'BLOG_DATA_DELETED';
export const BLOG_DATA_LOADED = 'BLOG_DATA_LOADED';
export const API_ERRORED = 'API_ERRORED';
